import type { Metadata } from "next";
import { Roboto } from "next/font/google";

import "./globals.css";

import { cn } from "@/utils/shadcn";

const roboto = Roboto({ 
  weight: ['300', '400', '500', '700'],
  subsets: ['latin', 'cyrillic'],  
  display: 'swap',
  variable: '--font-roboto',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={cn(
        "h-full",
        "antialiased",
        "font-sans",
        roboto.variable,
      )}
    >
      <body className="dark min-h-full flex flex-col">{children}</body>
    </html>
  );
}
