import type { Metadata } from "next";
import { Roboto } from "next/font/google";

import "./globals.css";

import { Toaster } from "@/components/ui/sonner";
import { Providers } from "@/provider/ApolloProvider";
import { cn } from "@/utils/shadcn";

const roboto = Roboto({
  weight: ["300", "400", "500", "700"],
  subsets: ["latin", "cyrillic"],
  display: "swap",
  variable: "--font-roboto",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={cn("h-full", "antialiased", roboto.variable)}>
      <body className="min-h-full flex flex-col">
        <Providers>{children}</Providers>

        <Toaster />
      </body>
    </html>
  );
}
