import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import { cookies } from "next/headers";

import "./globals.css";

import { ThemeProvider } from "@/components/providers";
import { Toaster } from "@/components/ui/sonner";
import { Language } from "@/constants/translations";
import { LanguageProvider } from "@/context/language";
import { Providers } from "@/provider/ApolloProvider";
import { cn } from "@/utils/shadcn";

const roboto = Roboto({
  weight: ["300", "400", "500", "700"],
  subsets: ["latin", "cyrillic"],
  display: "swap",
  variable: "--font-roboto",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookieStore = await cookies();
  const savedLang = cookieStore.get("app_language")?.value as Language;
  const initialLanguage: Language = savedLang === "ru" ? "ru" : "en";

  return (
    <html
      lang={initialLanguage}
      suppressHydrationWarning
      className={cn("h-full", "antialiased", roboto.variable)}
    >
      <body className="min-h-screen">
        <LanguageProvider initialLanguage={initialLanguage}>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <Providers>
              {children}
            </Providers>
          </ThemeProvider>

          <Toaster />
        </LanguageProvider>
      </body>
    </html>
  );
}
